paths:
  project_root: 'D:/python_projects/world_info'
  data_root: 'D:/python_projects/world_info/data'
  raw_folder: 'D:/python_projects/world_info/data/raw'

database_paths:
  bronze: 'D:/python_projects/world_info/data/bronze'
  silver: 'D:/python_projects/world_info/data/silver'

raw_paths:
  unodc_func_justice: 'D:/python_projects/world_info/data/raw/data_cts_access_and_functioning_of_justice/data_cts_access_and_functioning_of_justice.xlsx'
  unodc_econ_crime: 'D:/python_projects/world_info/data/raw/data_cts_corruption_and_economic_crime/data_cts_corruption_and_economic_crime.xlsx'
  unodc_sexual_violent: 'D:/python_projects/world_info/data/raw/data_cts_violent_and_sexual_crime/data_cts_violent_and_sexual_crime.xlsx'
  wb_edstats: 'D:/python_projects/world_info/data/raw/Edstats_Updated/Edstats_Updated.csv'
  wb_gem_cpi_yoy_nominal: 'D:/python_projects/world_info/data/raw/GemDataEXTR/unzipped/CPI Price, % y-o-y, nominal, seas. adj..xlsx'
  wb_gem_core_cpi_seas_adj: 'D:/python_projects/world_info/data/raw/GemDataEXTR/unzipped/Core CPI, seas. adj..xlsx'
  wb_real_exchange_rate: 'D:/python_projects/world_info/data/raw/GemDataEXTR/unzipped/Real Effective Exchange Rate.xlsx'
  wb_official_exchange_rate: 'D:/python_projects/world_info/data/raw/GemDataEXTR/unzipped/Official exchange rate, LCU per USD, period average.xlsx'
  wb_gdp_current:  'D:/python_projects/world_info/data/raw/GemDataEXTR/unzipped/GDP at market prices, constant 2010 US$, millions, seas. adj..xlsx'
  wb_gdp_constant: 'D:/python_projects/world_info/data/raw/GemDataEXTR/unzipped/GDP at market prices, current US$, millions, seas. adj..xlsx'
  wb_export_merch: 'D:/python_projects/world_info/data/raw/GemDataEXTR/unzipped/Exports Merchandise, Customs, current US$, millions, seas. adj..xlsx'
  wb_import_merch: 'D:/python_projects/world_info/data/raw/GemDataEXTR/unzipped/Imports Merchandise, Customs, current US$, millions, seas. adj..xlsx'
  wb_unemployment: 'D:/python_projects/world_info/data/raw/GemDataEXTR/unzipped/Unemployment Rate, seas. adj..xlsx'
  wb_industrial_production: 'D:/python_projects/world_info/data/raw/GemDataEXTR/unzipped/Industrial Production, constant 2010 US$, seas. adj..xlsx'
  wb_total_reserves: 'D:/python_projects/world_info/data/raw/GemDataEXTR/unzipped/Total Reserves.xlsx'
  wb_stock_markets: 'D:/python_projects/world_info/data/raw/GemDataEXTR/unzipped/Stock Markets, US$.xlsx'
  wb_foreign_reserves: 'D:/python_projects/world_info/data/raw/GemDataEXTR/unzipped/Foreign Reserves, Months Import Cover, Goods.xlsx'
  wb_retail_sales_volume_index: 'D:/python_projects/world_info/data/raw/GemDataEXTR/unzipped/Retail Sales Volume Index, seas. adj..xlsx'
  wb_gender_stats: 'D:/python_projects/world_info/data/raw/Gender_Stats_CSV/unzipped/Gender_StatsCSV.csv'
  wb_gender_stats_country: 'D:/python_projects/world_info/data/raw/Gender_Stats_CSV/unzipped/Gender_StatsCountry.csv'
  wb_gender_stats_series: 'D:/python_projects/world_info/data/raw/Gender_Stats_CSV/unzipped/Gender_StatsSeries.csv'
  wb_hnp_stats: 'D:/python_projects/world_info/data/raw/HNP_Stats_CSV/unzipped/HNP_StatsCSV.csv'
  wb_hnp_stats_series: 'D:/python_projects/world_info/data/raw/HNP_Stats_CSV/unzipped/HNP_StatsSeries.csv'
  wb_hnp_stats_country: 'D:/python_projects/world_info/data/raw/HNP_Stats_CSV/unzipped/HNP_StatsCountry.csv'
  wb_ids_stats: 'D:/python_projects/world_info/data/raw/IDS_CSV/unzipped/IDS_ALLCountries_Data.csv'
  wb_ids_series: 'D:/python_projects/world_info/data/raw/IDS_CSV/unzipped/IDS_SeriesMetaData.csv'
  wb_ids_country: 'D:\python_projects\world_info\data\raw\IDS_CSV\unzipped\IDS_CountryMetaData.csv'
  wb_jobs_stats: 'D:/python_projects/world_info/data/raw/Jobs_CSV/unzipped/JobsCSV.csv'
  wb_jobs_country: 'D:/python_projects/world_info/data/raw/Jobs_CSV/unzipped/JobsCountry.csv'
  wb_jobs_series: 'D:/python_projects/world_info/data/raw/Jobs_CSV/unzipped/JobsSeries.csv'

bronze_table_paths: 
  unodc_func_justice: 'D:/python_projects/world_info/data/bronze/unodc_func_justice'
  unodc_econ_crime: 'D:/python_projects/world_info/data/bronze/unodc_econ_crime'
  unodc_sexual_violent: 'D:/python_projects/world_info/data/bronze/unodc_sexual_violent'
  wb_edstats: 'D:/python_projects/world_info/data/bronze/wb_edstats'
  wb_gem_cpi_yoy_nominal_annual: 'D:/python_projects/world_info/data/bronze/wb_gem_cpi_yoy_nominal_annual'
  wb_gem_cpi_yoy_nominal_monthly: 'D:/python_projects/world_info/data/bronze/wb_gem_cpi_yoy_nominal_monthly'
  wb_gem_core_cpi_seas_adj_annual: 'D:/python_projects/world_info/data/bronze/wb_gem_core_cpi_seas_adj_annual'
  wb_gem_core_cpi_seas_adj_monthly: 'D:/python_projects/world_info/data/bronze/wb_gem_core_cpi_seas_adj_monthly'
  wb_real_exchange_rate_annual: 'D:/python_projects/world_info/data/bronze/wb_real_exchange_rate_annual'
  wb_real_exchange_rate_monthly: 'D:/python_projects/world_info/data/bronze/wb_real_exchange_rate_monthly'
  wb_official_exchange_rate_annual: 'D:/python_projects/world_info/data/bronze/wb_official_exchange_rate_annual'
  wb_official_exchange_rate_monthly: 'D:/python_projects/world_info/data/bronze/wb_official_exchange_rate_monthly'
  wb_gdp_current_annual: 'D:/python_projects/world_info/data/bronze/wb_gdp_current_annual'
  wb_gdp_current_quarterly: 'D:/python_projects/world_info/data/bronze/wb_gdp_current_quarterly'
  wb_gdp_constant_annual: 'D:/python_projects/world_info/data/bronze/wb_gdp_constant_annual'
  wb_gdp_constant_quarterly: 'D:/python_projects/world_info/data/bronze/wb_gdp_constant_quarterly'
  wb_import_merch_annual: 'D:/python_projects/world_info/data/bronze/wb_import_merch_annual'
  wb_import_merch_quarterly: 'D:/python_projects/world_info/data/bronze/wb_import_merch_quarterly'
  wb_import_merch_monthly: 'D:/python_projects/world_info/data/bronze/wb_import_merch_monthly'
  wb_export_merch_annual: 'D:/python_projects/world_info/data/bronze/wb_export_merch_annual'
  wb_export_merch_quarterly: 'D:/python_projects/world_info/data/bronze/wb_export_merch_quarterly'
  wb_export_merch_monthly: 'D:/python_projects/world_info/data/bronze/wb_export_merch_monthly'
  wb_unemployment_annual: 'D:/python_projects/world_info/data/bronze/wb_unemployment_annual'
  wb_unemployment_monthly: 'D:/python_projects/world_info/data/bronze/wb_unemployment_monthly'
  wb_industrial_production_annual: 'D:/python_projects/world_info/data/bronze/wb_industrial_production_annual'
  wb_industrial_production_monthly: 'D:/python_projects/world_info/data/bronze/wb_industrial_production_monthly'
  wb_total_reserves_annual: 'D:/python_projects/world_info/data/bronze/wb_total_reserves_annual'
  wb_total_reserves_monthly: 'D:/python_projects/world_info/data/bronze/wb_total_reserves_monthly'
  wb_stock_markets_annual: 'D:/python_projects/world_info/data/bronze/wb_stock_markets_annual'
  wb_stock_markets_monthly: 'D:/python_projects/world_info/data/bronze/wb_stock_markets_monthly'
  wb_foreign_reserves_annual: 'D:/python_projects/world_info/data/bronze/wb_foreign_reserves_annual'
  wb_foreign_reserves_monthly: 'D:/python_projects/world_info/data/bronze/wb_foreign_reserves_monthly'
  wb_retail_sales_volume_index_annual: 'D:/python_projects/world_info/data/bronze/wb_retail_sales_volume_index_annual'
  wb_retail_sales_volume_index_monthly: 'D:/python_projects/world_info/data/bronze/wb_retail_sales_volume_index_monthly'
  wb_gender_stats: 'D:/python_projects/world_info/data/bronze/wb_gender_stats'
  wb_hnp_stats: 'D:/python_projects/world_info/data/bronze/wb_hnp_stats'
  wb_ids_stats: 'D:/python_projects/world_info/data/bronze/wb_ids_stats'
  wb_jobs_stats: 'D:/python_projects/world_info/data/bronze/wb_jobs_stats'
  wb_non_gem_countries: 'D:/python_projects/world_info/data/bronze/wb_non_gem_countries'
  wb_non_gem_indicators: 'D:/python_projects/world_info/data/bronze/wb_non_gem_indicators'


silver_table_paths:
  dim_country_unodc: 'D:/python_projects/world_info/data/silver/dim_country_unodc'
  fact_crime_and_justice_unodc: 'D:/python_projects/world_info/data/silver/fact_crime_and_justice_unodc'
  fact_gem_annual: 'D:/python_projects/world_info/data/silver/fact_gem_annual'
  fact_gem_monthly: 'D:/python_projects/world_info/data/silver/fact_gem_monthly'
  fact_gem_quarterly: 'D:/python_projects/world_info/data/silver/fact_gem_quarterly'
  fact_wb_edstats: 'D:/python_projects/world_info/data/silver/fact_wb_edstats'
  dim_country_wb: 'D:/python_projects/world_info/data/silver/dim_country_wb'
  dim_indicator_wb: 'D:/python_projects/world_info/data/silver/dim_indicator_wb'
  fact_wb_stats_non_gem: 'D:/python_projects/world_info/data/silver/fact_wb_stats_non_gem'

gold_table_paths:
  dim_country: 'D:/python_projects/world_info/data/gold/dim_country'
  fact_unodc_crime_global: 'D:/python_projects/world_info/data/gold/fact_unodc_crime_global'
  fact_wb_gem_all_data: 'D:/python_projects/world_info/data/gold/fact_wb_gem_all_data'
  fact_wb_non_gem_all_data: 'D:/python_projects/world_info/data/gold/fact_wb_non_gem_all_data'
  fact_edstats: 'D:/python_projects/world_info/data/gold/fact_edstats'


spark:
  warehouse_dir: 'D:/python_projects/world_info.data'
